// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UID          int32  `gorm:"column:uID;primaryKey;autoIncrement:true" json:"uID"`
	Name         string `gorm:"column:name;not null;comment:昵称" json:"name"`        // 昵称
	Introduction string `gorm:"column:introduction;comment:简介" json:"introduction"` // 简介
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
